# version: '3'
# services:
#   db:
#     image: postgres
#     environment:
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_USER: postgres
#       POSTGRES_DB: job_board_api_pg
#     volumes:
#       - ./pg-data:/var/lib/postgresql/data/
#     ports:
#       - '5432:5432'

#   api:
#     build: ./
#     command: npm run dev:watch
#     ports:
#       - '4000:4000'
#     volumes: 
#       - ./:/main/dist
#       - nodemodules:/main/node_modules
#     links: 
#       - db
#     depends_on:
#       - db
# volumes: 
#   nodemodules: {}

version: '3'
services:
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]
